#ifndef GRAPHICSMAPLIB_GLOBAL_H
#define GRAPHICSMAPLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHICSMAPLIB_LIBRARY)
#  define GRAPHICSMAPLIB_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHICSMAPLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHICSMAPLIB_GLOBAL_H
